<?php
session_start();
include_once "../includes/db-conn.php";

if (isset($_POST['create-new-blog'])) {
    $email = $_SESSION['current_user_email'];
    $title = $_POST['title'];
    $desc = $_POST['desc'];
    $eventDate = $_POST['event-date'];
    $visibility = getVisibility();

    $sql = 'INSERT INTO blogs (creator_email, title, description, event_date, privacy_filter) VALUE (?,?,?,?,?)';

    if ($stmt = $conn->prepare($sql)) {
        $stmt->bind_param('sssss', $email, $title, $desc, $eventDate, $visibility);
        
        if ($stmt->execute()) {
            // Get autogenerated blog ID and make directory.
            $blog_id = $conn->insert_id;
            $blog_dir = '../images/'.$blog_id;
            mkdir($blog_dir);
            $conn->close();
            
            // Add image to database (WIP)
            move_uploaded_file($_POST['new-blog-images'], $blog_dir);
            
            header('Location: ../index.php');
            exit;
        } else {
            echo 'Error: '.$stmt->error;
        }
        $stmt->close();
    }
    
}

function getVisibility() {
    if (isset($_POST['visibility'])) {
        return 'public';
    } else {
        return 'private';
    }
}
?>