<div class="modal fade" id="new-blog-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form id="new-blog-form" action="actions/new-blog.php" method="POST">
				
                <div class="modal-header">
					<h3>Create New Blog</h3>
				</div>

				<div class="modal-body">
                    <!-- Email from session -->

					<div class="form-group">
						<label>Title</label>
						<input type="text" name="title" class="form-control" required="">
					</div>

                    <div class="form-group">
						<label>Description</label>
						<input type="text" name="desc" class="form-control" required="">
					</div>

                    <div class="form-group">
                        <!-- Need to implement a way to send blog image. -->
						<label>Upload Images</label>
						<input type="file" name="new-blog-images" class="form-control" required="">
					</div>

                    <div class="form-group">
						<label>Event Date</label>
						<input type="datetime-local" name="event-date" class="form-control" required="">
					</div>

                    <!-- Creation & Last Modified Date (Generated by table) -->

				</div>

				<div class="modal-footer">
					<input type="submit" name="create-new-blog" value="Post Blog" class="btn btn-primary">

                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" id="visibility">
                        <label class="form-check-label" for="visibility">Public</label>
                    </div>
				</div>

			</form>
		</div>
	</div>
</div>